### ISSUE TITLE
Error team-services-extension  

### ISSUE THREAD

**Issue by rameshmaruthi80** [ALM-Rangers/generator-team-services-extension#11]
You don’t seem to have a generator with the name “team-services-extension:widget” installed.  From these template the dashboard widget is not getting installed.

PS p> yo --help
Usage: yo GENERATOR [args] [options]

General options:
  --help         # Print this info and generator's options and usage
  -f, --force    # Overwrite files that already exist
  --version      # Print version
  --no-color     # Disable colors
  --[no-]insight # Toggle anonymous tracking
  --generators   # Print available generators

Install a generator:

  Generators can be installed through npm.

  $ npm install generator-angular
  $ yo angular --help

Completion:

  To enable shell completion for the yo command, try running

  $ yo completion

Troubleshooting:

  For any issues, try running

  $ yo doctor

Full Documentation: http://yeoman.io

Available Generators:
  team-services-extension
    hub
    taskitem

**Comment by wpschaub** [comment]
Resolved in #10 which will re released with v1.0.33.
