### ISSUE TITLE
throw er; // Unhandled 'error' event On MAC OS

### ISSUE THREAD

**Issue by hkamel** [ALM-Rangers/generator-team-services-extension#12]
**On macOS**
Trying to generate a build/release task using the generator version v.1.0.33 getting the above mentioned error.

![screenshot](https://yiascq.bn1302.livefilestore.com/y4mfUFE5K05K0yjyfGKG3mCCa3b4TafDZ6SdwSEYy0WILVoOOBraMBfUZmBLCoqpc-pFH9MbqfGcnCXVzsgVQAnVqmo_vwsm_FgaYg4yunFj2GRXH5s4TrIOSqdFG73HcFEVehaT38lNKRMB_LkOhgxXyHjNcYQ7MBVbjQGI-WcA6fqGZfBqRII1qg8p4cCqTtreKnev3kL4Im1C2qnUOoPvg?width=1036&height=999&cropmode=none)

**Here is the full trace** 

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, uv_chdir
    at process.chdir (/usr/local/lib/node_modules/yo/node_modules/graceful-fs/polyfills.js:21:9)
    at process.chdir (/usr/local/lib/node_modules/generator-team-services-extension/node_modules/graceful-fs/polyfills.js:21:9)
    at child.install (/usr/local/lib/node_modules/generator-team-services-extension/generators/taskitem/index.js:254:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-team-services-extension/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-team-services-extension/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/generator-team-services-extension/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-team-services-extension/node_modules/yeoman-generator/lib/base.js:432:9
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
hkamels-MBP:~ hkamel$

**Comment by mikaelkrief** [comment]
Hi
What is your NodeJs and npm version ?

**Comment by hkamel** [comment]
npm 4.2.0

NodeJs 7.10.0

**Comment by mikaelkrief** [comment]
Could you try with LTS (6.10.3) version of nodejs

![image](https://cloud.githubusercontent.com/assets/2725302/25849759/0824735a-34c0-11e7-8f72-1b158df102fb.png)

On my side, I will try with 7.10.0 version

Thanks

**Comment by mikaelkrief** [comment]
working for me with v7.10.0 version.

Could you try to, inside the folder that yeoman had generated your extension, run the command "npm run package" and see the result

**Comment by hkamel** [comment]
_**npm run package**_ runs successfully with no issue and when running the same generator version and node v7.10.0 on Windows it run successfully as well. **_I believe this is an issue with the generator running on macOS._**

#### I'll do a further testing on macOS and update the thread.

![YoWindows](https://qmqhtg.bn1302.livefilestore.com/y4mlVDMKvfAtSoK5WyWLvDimRGKx6hNB6xkxqyIkIV4a9uBn3YjCKGxzhDn7sX34q2XSp6rrf-3k4W6jU_Fw37TMcM3YH04EWbJ5pHrfptBPgE6HJq_raa8zEN-xxz4QLhaP8E5WTYwU1HgbZad9yAsj9npshZnngzkYdZYBN9SBWK8KLJe_Hrmj56ph9Zup6JZkUZLytgFu3jSHjdLalHGmg?width=979&height=883&cropmode=none)

**Comment by hkamel** [comment]
I can confirm that the issue is now fixed with **v1.0.35** ... Thanks
