### ISSUE TITLE
Do we need the .vs folder?

### ISSUE THREAD

**Issue by wpschaub** [ALM-Rangers/generator-team-services-extension#18]
@mikaelkrief, do we really need the .vs folder or can we suppress and remove it?

**Comment by mikaelkrief** [comment]
no, we can suppress it and add it inside the .gitignore

**Comment by wpschaub** [comment]
Let’s do that in the next release.

PS: You have two releases to approve for PROD.

willy schaub

**Comment by mikaelkrief** [comment]
Approved ☺

Best Regards
Mikael Krief

De : Willy-Peter Schaub [mailto:notifications@github.com]
Envoyé : mercredi 7 juin 2017 15:52
À : ALM-Rangers/generator-team-services-extension <generator-team-services-extension@noreply.github.com>
Cc : Mikael <krief_mikael@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [ALM-Rangers/generator-team-services-extension] Do we need the .vs folder? (#18)

Let’s do that in the next release.

PS: You have two releases to approve for PROD.

willy schaub
