### ISSUE TITLE
Apply appropriate VSTS branding guidelines

### ISSUE THREAD

**Issue by willsmythe** [ALM-Rangers/generator-team-services-extension#25]
Use "Visual Studio Team Services (VSTS)" when first introducing, then use "VSTS". It's also acceptable to use "Visual Studio Team Services". Avoid "Team Services" and "VS Team Services".

This applies to the README, repo description, and text presented by the generator itself.

**Comment by wpschaub** [comment]
@willsmythe please review this PR https://github.com/ALM-Rangers/generator-vsts-extension/pull/26. It addresses the README, repo name, repo description, and text presented by generator.

**Comment by wpschaub** [comment]
@willsmythe we published https://github.com/ALM-Rangers/generator-vsts-extension/pull/26 after making a few additional branding tweaks. We'll re-visit a rename of the generator name at a later stage.
