### ISSUE TITLE
gruntfile.js is missing even though it is explicitly listed in the readme

### ISSUE THREAD

**Issue by StanislawSwierc** [ALM-Rangers/generator-team-services-extension#27]
Readme lists gruntfile.js as part of the template, but this file does not appear as one of the ouput.

https://github.com/ALM-Rangers/generator-vsts-extension/blob/master/generators/hub/templates/readme.md

**Comment by jeffrey-opdam** [comment]
We have deprecated the generator, therefor we are closing this issue.
