### ISSUE TITLE
Extension friendly name is used for directory/file names instead of ID

### ISSUE THREAD

**Issue by aelij** [ALM-Rangers/generator-team-services-extension#6]
Not sure if this was intentional, but personally I'd rather not have spaces in the file system... :)
It's also inconsistent - tasks use their IDs rather than friendly names.

**Comment by wpschaub** [comment]
Thank you for your feedback. We are planning to review the template extension architecture and address the "tasks use ID" in this (S116) sprint. We'll post a plan of action for the generator on https://aka.ms/vsarblog shortly.

**Comment by wpschaub** [comment]
@mikaelkrief can we close this issue?

**Comment by wpschaub** [comment]
Thanks for confirming.

**Comment by wpschaub** [comment]
Fix is in https://github.com/ALM-Rangers/generator-team-services-extension/pull/8.

**Comment by wpschaub** [comment]
Issue resolved with PR #8 and #9. Published as v1.0.23.
